spring:
  application:
    name: copiedvelog
  datasource:
    url: jdbc:mysql://localhost:3308/exampldb
    username: zenk555
    password: pae5554785
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv23liRKxUsHQSMDq2Ef
            client-secret: 8a79f78504de5d72ec865584445bdf8890ac47d7
            scope:
              - read:user
              - user:email
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

server:
  port: 80
  servlet:
    session:
      timeout: 30m
  tomcat:
    threads:
      max: 250
      min-spare: 20

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012
