spring:
  application:
    name: copiedvelog
  datasource:
    url: jdbc:mysql://localhost:3308/exampldb
    username: zenk555
    password: pae5554785
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 80
  servlet:
    session:
      timeout: 30m
  tomcat:
    threads:
      max: 250
      min-spare: 20

logging:
  file:
    name: logs/spring-boot-application.log
  level:
    org.example: DEBUG

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012