POST http://localhost/api/user/login
Content-Type: application/json

{
  "username": "123",
  "password": "123"
}

###
GET http://localhost/api/authtest

###
GET http://localhost/api/authtest
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjMiLCJ1c2VySWQiOjIyLCJuYW1lIjoiMTIzIiwidXNlcm5hbWUiOiIxMjMiLCJyb2xlcyI6W10sImlhdCI6MTcxOTk5NTI0MSwiZXhwIjoxNzE5OTk3MDQxfQ.VVGn1iHoP9aho6M0uxLeM_HU2xuTUGYgd9fAAGoufjI

###
GET http://localhost:8080/api/authtest
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjMiLCJ1c2VySWQiOjIyLCJuYW1lIjoiMTIzIiwidXNlcm5hbWUiOiIxMjMiLCJyb2xlcyI6W10sImlhdCI6MTcxOTk4OTk1NSwiZXhwIjoxNzE5OTkxNzU1fQ.Qyeku4PcZDfGV3xao4plyLXlyTTHqyRiNe4xtPZv7VM

###
POST http://localhost:8080/refreshToken
Cookie: refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjMiLCJ1c2VySWQiOjIyLCJuYW1lIjoiMTIzIiwidXNlcm5hbWUiOiIxMjMiLCJyb2xlcyI6W10sImlhdCI6MTcxOTk4OTk1NSwiZXhwIjoxNzIwNTk0NzU1fQ.8akYWSrS_raOjYMNQcFlwozpdyEhD0ajKJvB6F5P7Ss

